sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: HF9SNDTtgkayW9siKPSU7jMctHSNMH
    access-key-id: LTAI5tEKnjoSBjM26x4XMd28
    bucket-name: sky-takeout-yue

  redis:
    host: 127.0.0.1
    port: 6379  # 默认值
    password: 1234
    database: 0  # 默认值，DB0;
    timeout: 10000

  wechat:
    appid: wxdfbd31f9dc19a740
    secret: 115f640176a3a22bba6f71989fed525e
    # 微信支付功能配置
    mchid: 1561414331  # 自己申请的商务号
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606  # 证书序列号
    privateKeyFilePath: D:\apiclient_key.pem  # 私钥文件
    apiV3Key: CZBK51236435wxpay435434323FFDuv3  # 解密密钥，从商务平台获得
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem  # 平台证书文件
    notifyUrl: https://www.weixin.qq.com/notify/paySuccess  # 支付成功的回调地址(微信后台发起)，需要替换临时域名(https://www.weixin.qq.com)+controller的请求路径(/notify/paySuccess)
    refundNotifyUrl: https://www.weixin.qq.com/notifyrefundSuccess  # 退款成功回调地址